name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: write
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1000

    env:
      JULIA_NUM_THREADS: 1
      JULIA_PKG_PRECOMPILE_AUTO: 0
      LIBGL_ALWAYS_SOFTWARE: 1

    steps:
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'
      - name: Install binary dependencies
        run: sudo apt-get update && sudo apt-get install -y \
             xorg-dev mesa-utils xvfb libgl1 freeglut3-dev \
             libxrandr-dev libxinerama-dev libxcursor-dev \
             libxi-dev libxext-dev

      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.11"

      - name: Install dependencies
        run: >
            DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
            julia --project=. --compiled-modules=no --startup-file=no -e 'using Pkg; Pkg.instantiate(); GC.gc(true);'

      - name: Run Tests
        run: >
            DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
            julia --project=. --compiled-modules=no --startup-file=no -e 'using Pkg; GC.gc(true); Pkg.test(; coverage=false)'